import {
  ArrowDown as ArrowDownwardIcon,
  ArrowLeftRight as SyncAltIcon,
  ArrowRight as ArrowRightIcon,
  ArrowUpDown as SortIcon,
  ChevronDown as ExpandMoreIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronsDown as KeyboardDoubleArrowDownIcon,
  ChevronsLeft as FirstPageIcon,
  ChevronsRight as LastPageIcon,
  Columns3 as ViewColumnIcon,
  Copy as ContentCopy,
  EyeOff as VisibilityOffIcon,
  Filter as FilterAltIcon,
  FilterX as FilterListOffIcon,
  GripHorizontal as DragHandleIcon,
  Layers as DynamicFeedIcon,
  ListFilter as FilterListIcon,
  ListX as ClearAllIcon,
  Maximize2 as FullscreenIcon,
  Minimize2 as FullscreenExitIcon,
  MoreHorizontal as MoreHorizIcon,
  MoreVertical as MoreVertIcon,
  Pencil as EditIcon,
  Pin as PushPinIcon,
  RotateCcw as RestartAltIcon,
  Rows2 as DensityLargeIcon,
  Rows3 as DensityMediumIcon,
  Rows4 as DensitySmallIcon,
  Save as SaveIcon,
  Search as SearchIcon,
  SearchX as SearchOffIcon,
  X as CloseIcon,
  XCircle as CancelIcon,
} from 'lucide-react';

export const SST_Default_Icons = {
  ArrowDownwardIcon,
  ArrowRightIcon,
  CancelIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ClearAllIcon,
  CloseIcon,
  ContentCopy,
  DensityLargeIcon,
  DensityMediumIcon,
  DensitySmallIcon,
  DragHandleIcon,
  DynamicFeedIcon,
  EditIcon,
  ExpandMoreIcon,
  FilterAltIcon,
  FilterListIcon,
  FilterListOffIcon,
  FirstPageIcon,
  FullscreenExitIcon,
  FullscreenIcon,
  KeyboardDoubleArrowDownIcon,
  LastPageIcon,
  MoreHorizIcon,
  MoreVertIcon,
  PushPinIcon,
  RestartAltIcon,
  SaveIcon,
  SearchIcon,
  SearchOffIcon,
  SortIcon,
  SyncAltIcon,
  ViewColumnIcon,
  VisibilityOffIcon,
} as const;

export type SST_Icons = Record<keyof typeof SST_Default_Icons, any>;
